version: '3'
services:
  app:
    image: app
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - mypostgres
    links:
      - mypostgres
  mypostgres:
    image: postgres
    container_name: mypostgres
    ports:
      - "5600:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=springbootdemo


